// @generated by `cargo xtask codegen-api` -- DO NOT EDIT.
// Source: vendor/godot/4.5-stable/extension_api.json
//
// Phase 0 emits only this minimal metadata; Phase 2 grows it into the full engine model.

/// The Godot version this engine-API artifact was generated from.
pub const GODOT_VERSION: &str = "4.5.0-stable";

/// Number of engine classes in the source `extension_api.json`.
pub const CLASS_COUNT: usize = 971;

/// Number of built-in (Variant) types in the source `extension_api.json`.
pub const BUILTIN_CLASS_COUNT: usize = 38;
