//! `gdscript-api` — the Godot engine model, generated from `extension_api.json`.
//!
//! The full model (engine classes + inheritance chain, methods, properties, signals, enums,
//! constants, singletons, utility functions, builtin Variant types) plus the hand-authored
//! GDScript layer the dump omits (keywords, annotations, builtins) lands in Phase 2.
//!
//! Phase 0 carries only a minimal generated metadata artifact (Godot version + class counts),
//! produced by `cargo xtask codegen-api` from the newest `vendor/godot/<version>/extension_api.json`.
//! This proves the vendored-JSON → codegen → crate pipeline end-to-end. Must build for `wasm32`.
#![cfg_attr(docsrs, feature(doc_cfg))]

/// Generated engine-API metadata. Produced by `cargo xtask codegen-api`; do not edit by hand.
pub mod generated;

/// The Godot version string the bundled engine-API artifact was generated from.
#[must_use]
pub fn godot_version() -> &'static str {
    generated::GODOT_VERSION
}

#[cfg(test)]
mod tests {
    #[test]
    fn generated_metadata_is_present() {
        // Regenerated by `cargo xtask codegen-api`; the version string is always populated.
        assert!(!crate::generated::GODOT_VERSION.is_empty());
    }
}
