// Phase-5 demo (Node path): load the native binding, push `.gd` files by URI, and print
// diagnostics / symbols / completions — plus a cross-file `preload` resolution. Build the addon
// first with `npm run build` (requires @napi-rs/cli, which provisions libnode on Windows).
//
//   cd bindings/node && npm install && npm run build && npm run demo

// napi-rs emits a CommonJS `index.js` (generated by `napi build --platform`); load it from this
// ES module via createRequire.
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const { AnalysisHandle } = require("./index.js");

const SRC = `class_name Player extends CharacterBody2D

const SPEED := 300.0
@export var health: int = 100
signal died(reason: String)
enum State { IDLE, RUNNING }

func _ready() -> void:
	var node := $Sprite2D
	print(node, health)

class Inner:
	var x = 1
	func helper() -> int:
		return x
`;

const handle = new AnalysisHandle();
const URI = "inmemory://player.gd";
// The URI-keyed lifecycle: open a document (optionally with its res:// path for cross-file work).
handle.openDocument(URI, SRC, null);

console.log("=== diagnostics ===");
console.log(handle.diagnostics(URI)); // [] for valid source

console.log("\n=== document symbols ===");
const symbols = JSON.parse(handle.documentSymbols(URI));
function printSym(sym, depth = 0) {
  console.log(
    `${"  ".repeat(depth)}${sym.kind.padEnd(9)} ${sym.name}  @${sym.range.start}..${sym.range.end}`,
  );
  for (const child of sym.children) printSym(child, depth + 1);
}
for (const sym of symbols) printSym(sym);

console.log("\n=== completions at end of file ===");
// The analyzer takes a BYTE offset; SRC is ASCII here, so its UTF-16 length is the byte length.
const items = JSON.parse(handle.completions(URI, SRC.length));
console.log(items.slice(0, 8).map((i) => `${i.kind}:${i.label}`).join(", "), "…");

console.log("\n=== cross-file preload resolution (the URI + res:// path API) ===");
// markup.gd defines a class_name with a typed method; main.gd preloads it by res:// path. The
// shared AnalysisHost resolves `M.new().parse()` cross-file → `n` is typed `int` (an inlay proves
// it; an unresolved preload would leave `n` untyped and suppress the hint).
handle.openDocument(
  "inmemory://markup.gd",
  "class_name Markup\nfunc parse() -> int:\n\treturn 1\n",
  "res://markup.gd",
);
const MAIN = 'const M = preload("res://markup.gd")\nfunc go():\n\tvar n := M.new().parse()\n';
handle.openDocument("inmemory://main.gd", MAIN, "res://main.gd");
const mainDiags = JSON.parse(handle.diagnostics("inmemory://main.gd"));
const hints = JSON.parse(handle.inlayHints("inmemory://main.gd"));
console.log(`main.gd diagnostics: ${mainDiags.length} (expect 0)`);
console.log(`main.gd inlay hints: ${hints.map((h) => h.label).join(", ")} (expect an ": int")`);
