//! Implementations of the `cargo xtask <command>` subcommands.

use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result, bail};

/// `cargo xtask ci` — the one-shot local gate mirroring `.github/workflows/ci.yml`.
pub fn ci() -> Result<()> {
    section("fmt");
    run(cargo().args(["fmt", "--all", "--", "--check"]))?;

    section("clippy");
    run(cargo().args([
        "clippy",
        "--all-targets",
        "--all-features",
        "--",
        "-D",
        "warnings",
    ]))?;

    section("test");
    // No `--workspace`: `default-members` excludes the FFI bindings, which build on
    // their own targets (napi via @napi-rs/cli, wasm via wasm-pack).
    run(cargo().args(["test"]))?;

    section("wasm-check");
    // The core public surface and the browser binding must both build on wasm32.
    run(cargo().args([
        "check",
        "-p",
        "gdscript-ide",
        "--target",
        "wasm32-unknown-unknown",
    ]))?;
    run(cargo().args([
        "build",
        "-p",
        "gdscript-wasm",
        "--target",
        "wasm32-unknown-unknown",
    ]))?;

    section("deny");
    // `cargo-deny` is enforced as its own CI job; locally it is best-effort (warn if absent) so the
    // gate runs even when a contributor has not installed the plugin.
    if let Err(err) = run(cargo().args(["deny", "check"])) {
        eprintln!("warning: skipping `cargo deny` ({err})");
    }

    println!("\nCI gate passed.");
    Ok(())
}

/// `cargo xtask codegen-api` — regenerate `gdscript-api`'s engine model from the newest
/// vendored `extension_api.json`: normalize it (`codegen.rs`), `rkyv`-encode it to the bundled
/// blob, and refresh the `generated.rs` metadata. See Playbook §4.
pub fn codegen_api() -> Result<()> {
    let root = workspace_root();
    let vendor = root.join("vendor").join("godot");
    let version_dir = newest_vendor_dir(&vendor)?;
    let json_path = version_dir.join("extension_api.json");
    let dir_name = version_dir
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();

    let json = std::fs::read_to_string(&json_path)
        .with_context(|| format!("reading {}", json_path.display()))?;
    let generated = crate::codegen::generate(&json)?;

    let api_dir = root.join("crates").join("gdscript-api").join("src");

    let blob_path = api_dir.join("engine_api.bin");
    std::fs::write(&blob_path, &generated.blob)
        .with_context(|| format!("writing {}", blob_path.display()))?;

    let crate::codegen::Generated {
        version,
        class_count,
        builtin_count,
        blob,
    } = &generated;
    let meta_path = api_dir.join("generated.rs");
    let contents = format!(
        "// @generated by `cargo xtask codegen-api` -- DO NOT EDIT.\n\
         // Source: vendor/godot/{dir_name}/extension_api.json\n\
         //\n\
         // The full engine model lives in the `rkyv` blob `engine_api.bin`; these are just\n\
         // fast compile-time constants for sanity checks and display.\n\
         \n\
         /// The Godot version this engine-API artifact was generated from.\n\
         pub const GODOT_VERSION: &str = \"{version}\";\n\
         \n\
         /// Number of engine classes in the source `extension_api.json`.\n\
         pub const CLASS_COUNT: usize = {class_count};\n\
         \n\
         /// Number of built-in (Variant) types in the source `extension_api.json`.\n\
         pub const BUILTIN_CLASS_COUNT: usize = {builtin_count};\n"
    );
    std::fs::write(&meta_path, contents)
        .with_context(|| format!("writing {}", meta_path.display()))?;

    println!(
        "codegen-api: wrote {} ({} bytes) + {} (godot {version}, {class_count} classes, {builtin_count} builtin types)",
        blob_path.display(),
        blob.len(),
        meta_path.display(),
    );
    Ok(())
}

/// `cargo xtask fixtures` — re-bless the golden fixtures (the `expect-test` `.cst`
/// snapshots) by running the tests with `UPDATE_EXPECT=1`. Review the diff before
/// committing.
pub fn fixtures() -> Result<()> {
    section("fixtures (bless)");
    run(cargo().env("UPDATE_EXPECT", "1").args(["test"]))?;
    println!("fixtures: regenerated golden files. Review the diff before committing.");
    Ok(())
}

/// `cargo xtask differential` — cross-validate the parser against tree-sitter-gdscript
/// (native-only; compiles tree-sitter's C parser). Divergences are triaged into
/// `crates/gdscript-syntax/tests/KNOWN_DIVERGENCES.md`.
pub fn differential() -> Result<()> {
    section("differential (vs tree-sitter)");
    run(cargo().args([
        "test",
        "-p",
        "gdscript-syntax",
        "--features",
        "tree-sitter-oracle",
        "--test",
        "differential",
    ]))?;
    Ok(())
}

/// `cargo xtask dist` — build the workspace + (empty) binding stubs end-to-end.
pub fn dist() -> Result<()> {
    section("build (release)");
    run(cargo().args(["build", "--workspace", "--release"]))?;
    println!("dist: Phase 0 builds the workspace + binding stubs.");
    println!("      Phase 1 wires `napi build` (Node) and the wasm target here.");
    Ok(())
}

/// `cargo xtask release [--dry-run]` — local release ergonomics. Publishing is CI-only (release-plz).
pub fn release(args: &[String]) -> Result<()> {
    if !args.iter().any(|a| a == "--dry-run") {
        println!("release: pass --dry-run. Actual publishing is done by CI (release-plz).");
        return Ok(());
    }
    section("release dry-run");
    let mut cmd = Command::new("release-plz");
    cmd.current_dir(workspace_root())
        .args(["update", "--dry-run"]);
    match cmd.status() {
        Ok(status) if status.success() => Ok(()),
        Ok(status) => bail!("release-plz update --dry-run failed: {status}"),
        Err(err) => {
            eprintln!("warning: release-plz not installed ({err}); skipping dry-run.");
            Ok(())
        }
    }
}

// ---- helpers ----

/// The workspace root (the parent of this `xtask` crate's manifest dir).
fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask is nested directly under the workspace root")
        .to_path_buf()
}

/// A `cargo` command rooted at the workspace, honoring the `CARGO` env var if cargo set it.
fn cargo() -> Command {
    let exe = std::env::var("CARGO").unwrap_or_else(|_| "cargo".to_owned());
    let mut cmd = Command::new(exe);
    cmd.current_dir(workspace_root());
    cmd
}

/// Run a command, turning a non-zero exit status into an error.
fn run(cmd: &mut Command) -> Result<()> {
    let status = cmd
        .status()
        .with_context(|| format!("failed to spawn {cmd:?}"))?;
    if !status.success() {
        bail!("command failed ({status}): {cmd:?}");
    }
    Ok(())
}

/// The newest vendored Godot API directory (lexicographically greatest name).
fn newest_vendor_dir(vendor: &Path) -> Result<PathBuf> {
    std::fs::read_dir(vendor)
        .with_context(|| format!("reading {}", vendor.display()))?
        .filter_map(std::result::Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .max()
        .with_context(|| format!("no vendored Godot API versions under {}", vendor.display()))
}

fn section(name: &str) {
    println!("== {name} ==");
}
